### ISSUE TITLE
BUG: mintscan.io maintained by @jackmatt2

### ISSUE THREAD

**Issue by TheRealSheHP** [jackmatt2/crypto-tax-exporter#2]
** Maintainer **
@jackmatt2 

- Using their Github username tag ensures they get a notification

** Name of provider **
mintscan.io

**Describe the bug**
Error, see screenshot, additional context 

**Console output & Network requests**

**To Reproduce**
Steps to reproduce the behaviour:
Everything
Akash
mintscan.io
Need the specific wallet address?

**Expected behaviour**
CSV file

**Screenshots**
![Screenshot_20230615_210959_com android chrome~2](https://github.com/jackmatt2/crypto-tax-exporter/assets/136768917/b4027679-7364-4365-8f2a-b2cbe499cd0c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Huawei 
- OS: android 
- Browser Chrome

**Additional context**
TypeError: Cannot read properties of undefined (reading 'messages')
If you beleive this error needs attention, create an issue on the [Github repository](https://github.com/jackmatt2/crypto-tax-exporter/issues/new?assignees=&labels=bug&template=bug_report.md&title=BUG:%20mintscan.io%20maintained%20by%20@jackmatt2) tagging @jackmatt2 (the maintainer of mintscan.io)

**Comment by jackmatt2** [comment]
Can you try it again? Try in incognito window if it fails again to ensure you get the latest resources.

**Comment by TheRealSheHP** [comment]
Same error message, even incognito

**Comment by TheRealSheHP** [comment]
Could a transaction having data in a comment field be causing an error,
because I think I made a transaction with a comment included at some point

**Comment by jackmatt2** [comment]
I don't think the comment field would have any affect on the current logic.

I realised that my `undefined` check was at the wrong level anyway.  Have updated to check for an `undefined` "data" attribute instead.

Can you try again - I have updated the code already.

**Comment by TheRealSheHP** [comment]
Okay, I got a file, no error! :)
Sending it to the accountant for review, hopefully the data will check out.
Will know in a few days.

Thank you, I'll keep you posted.
🙏
