### ISSUE TITLE
BUG: mintscan.io - the server responded with a status of 403

### ISSUE THREAD

**Issue by mnlytic** [jackmatt2/crypto-tax-exporter#5]
<img width="1188" alt="image" src="https://github.com/jackmatt2/crypto-tax-exporter/assets/12068740/eda271a1-847e-4a06-97e1-956b1191b7c0">

** Maintainer **
@jackmatt2 

- Using their Github username tag ensures they get a notification

** Name of provider **
Mintscan

**Describe the bug**
_TypeError: Spread syntax requires. iterable[Symbol. iterator] to be a function_
Comes up after 1 or 2 successfull CSV exports but works from time to time with the exact same settings / wallet adresses

**Console output & Network requests**
<img width="668" alt="image" src="https://github.com/jackmatt2/crypto-tax-exporter/assets/12068740/c12ebcea-80fc-4b24-b773-8d250d7561b1">

**Desktop (please complete the following information):**

- OS: MacOS 13.3.1 (a) (22E772610a)
- Browser Brave 1.57.47 Chromium: 116.0.5845.96

**Comment by jackmatt2** [comment]
Seems like their DDOS protection is interfering and starts blocking requests. I might need to start throttling the queries.

**Comment by mnlytic** [comment]
Would be awesome if they would whitelist your IP
Maybe that's possible?

**Comment by jackmatt2** [comment]
I added a rate limit of:
concurrency: 1
min execution time: 1/3 second

Can you try it out with your wallet and see how it goes?  I think corsproxy.io is rate limiting the request but can't find any documentation on what limits they use.

Can you try out the recent release and let me know if it's fixed? 

I might make the rate limits configurable ... eventually.

**Comment by mnlytic** [comment]
@jackmatt2 sry didn't see your comment from 2 weeks ago (just the closing notification).
Will try asap. Thank you!
